### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by tomtomprince** [bitLeague/project-site#7]
Specifically explain each answer, not just Goal = increase sales, how will you increase
sales

**Comment by tomtomprince** [comment]
Probably need to elaborate/add on to these. Let me know what you guys think

**Comment by financialdeveloper** [comment]
Goals likely refer to business goals and how we plan to reach them, not so much the planned features, as long as the features have business purpose. I've added my 3 goals to the document.

**Comment by tomtomprince** [comment]
That's true - let's go with yours
