### ISSUE TITLE
Communication Strategy

### ISSUE THREAD

**Issue by tomtomprince** [bitLeague/project-site#8]
### How to achieve Effective Communication among Project Team members
a. Transparent – Setting the right expectations and everyone knows what the other team members are doing
b. Reliable – Be present and respond in timely manner
c. Measurable – specific and well-defined methods and tools to measure how each
member is communicating effectively and contributing

**Comment by tomtomprince** [comment]
Document at https://drive.google.com/open?id=1OG7dBAAUXedosSVw0nsEoWrXiqA6uSr1c0q1F2khTWg for review

**Comment by financialdeveloper** [comment]
this looks great Tom. Will we be adding this to the powerpoint?

**Comment by tomtomprince** [comment]
Thanks Alex, I'll add a slide about it.
